-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.booking_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  from_status character varying,
  to_status character varying NOT NULL,
  changed_by character varying NOT NULL,
  changed_by_id uuid,
  notes text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT booking_tracking_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_number character varying NOT NULL DEFAULT ((('BK-'::text || to_char(now(), 'YYMMDD'::text)) || '-'::text) || lpad((floor((random() * (10000)::double precision)))::text, 4, '0'::text)) UNIQUE,
  customer_id uuid NOT NULL,
  provider_service_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  service_name_snapshot character varying NOT NULL,
  service_description_snapshot text,
  base_price_snapshot numeric NOT NULL,
  price_type_snapshot character varying NOT NULL,
  booking_date date NOT NULL CHECK (booking_date >= CURRENT_DATE),
  time_slot_start time without time zone NOT NULL,
  time_slot_end time without time zone NOT NULL,
  service_address text NOT NULL,
  service_city character varying NOT NULL,
  service_zip_code character varying,
  customer_latitude numeric,
  customer_longitude numeric,
  problem_description text,
  urgency character varying DEFAULT 'normal'::character varying CHECK (urgency::text = ANY (ARRAY['emergency'::character varying, 'urgent'::character varying, 'normal'::character varying]::text[])),
  special_instructions text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'confirmed'::character varying, 'scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'refunded'::character varying, 'disputed'::character varying]::text[])),
  total_amount numeric,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  final_amount numeric,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'refunded'::character varying, 'failed'::character varying]::text[])),
  payment_method character varying,
  provider_notes text,
  quoted_amount numeric,
  quote_valid_until timestamp with time zone,
  service_completed_at timestamp with time zone,
  customer_notes text,
  customer_rating integer CHECK (customer_rating >= 1 AND customer_rating <= 5),
  customer_review text,
  provider_rating integer CHECK (provider_rating >= 1 AND provider_rating <= 5),
  provider_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT bookings_provider_service_id_fkey FOREIGN KEY (provider_service_id) REFERENCES public.provider_services(id),
  CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT favorites_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  message_text text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'image'::character varying, 'file'::character varying, 'quote'::character varying]::text[])),
  attachment_url text,
  attachment_name character varying,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  notification_type character varying NOT NULL CHECK (notification_type::text = ANY (ARRAY['booking_request'::character varying, 'booking_accepted'::character varying, 'booking_rejected'::character varying, 'booking_confirmed'::character varying, 'booking_completed'::character varying, 'payment_received'::character varying, 'new_review'::character varying, 'message_received'::character varying, 'system_alert'::character varying, 'promotion'::character varying]::text[])),
  reference_type character varying,
  reference_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  payment_number character varying NOT NULL DEFAULT ((('PAY-'::text || to_char(now(), 'YYMMDD'::text)) || '-'::text) || lpad((floor((random() * (10000)::double precision)))::text, 4, '0'::text)) UNIQUE,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'INR'::character varying,
  payment_method character varying NOT NULL,
  transaction_id character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  failure_reason text,
  gateway_response jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT payments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  name text,
  user_type text DEFAULT 'customer'::text,
  services ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  category_id uuid NOT NULL,
  service_name character varying NOT NULL,
  service_description text,
  base_price numeric NOT NULL,
  price_type character varying DEFAULT 'fixed'::character varying CHECK (price_type::text = ANY (ARRAY['fixed'::character varying, 'hourly'::character varying, 'per_sqft'::character varying, 'custom'::character varying]::text[])),
  price_unit character varying,
  min_price numeric,
  max_price numeric,
  experience_years integer DEFAULT 0,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  service_images ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_services_pkey PRIMARY KEY (id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.quotations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  provider_id uuid NOT NULL,
  quote_amount numeric NOT NULL,
  labor_charges numeric,
  material_charges numeric,
  other_charges numeric,
  discount_percentage numeric DEFAULT 0,
  validity_days integer DEFAULT 7,
  payment_terms text,
  warranty_period character varying,
  status character varying DEFAULT 'sent'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])),
  customer_response character varying,
  response_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  CONSTRAINT quotations_pkey PRIMARY KEY (id),
  CONSTRAINT quotations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT quotations_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  reviewer_id uuid NOT NULL,
  reviewed_provider_id uuid,
  reviewed_customer_id uuid,
  reviewed_provider_user_id uuid,
  review_type character varying NOT NULL CHECK (review_type::text = ANY (ARRAY['customer_to_provider'::character varying, 'provider_to_customer'::character varying]::text[])),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text NOT NULL,
  rating_categories jsonb DEFAULT '{}'::jsonb,
  response_text text,
  response_date timestamp with time zone,
  status character varying DEFAULT 'published'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'published'::character varying, 'flagged'::character varying, 'hidden'::character varying, 'deleted'::character varying]::text[])),
  flagged_by_admin boolean DEFAULT false,
  flag_reason text,
  moderated_by uuid,
  moderated_at timestamp with time zone,
  is_verified_booking boolean DEFAULT true,
  verification_method character varying,
  helpful_votes integer DEFAULT 0,
  total_votes integer DEFAULT 0,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reviewed_provider_id_fkey FOREIGN KEY (reviewed_provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT reviews_reviewed_customer_id_fkey FOREIGN KEY (reviewed_customer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reviewed_provider_user_id_fkey FOREIGN KEY (reviewed_provider_user_id) REFERENCES public.users(id),
  CONSTRAINT reviews_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.users(id)
);
CREATE TABLE public.search_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  search_query text NOT NULL,
  search_filters jsonb,
  search_results_count integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT search_history_pkey PRIMARY KEY (id),
  CONSTRAINT search_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.service_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  is_recurring boolean DEFAULT true,
  specific_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_availability_pkey PRIMARY KEY (id),
  CONSTRAINT service_availability_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.service_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  icon character varying,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  business_name character varying,
  business_description text,
  business_logo text,
  business_phone character varying,
  business_email character varying,
  registration_number character varying,
  tax_id character varying,
  service_radius_km integer DEFAULT 10,
  service_cities ARRAY,
  total_jobs_completed integer DEFAULT 0,
  avg_rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  response_rate numeric DEFAULT 0,
  is_available boolean DEFAULT true,
  availability_status character varying DEFAULT 'available'::character varying CHECK (availability_status::text = ANY (ARRAY['available'::character varying, 'busy'::character varying, 'offline'::character varying]::text[])),
  is_verified boolean DEFAULT false,
  verification_documents ARRAY,
  bank_account_number character varying,
  bank_name character varying,
  ifsc_code character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_providers_pkey PRIMARY KEY (id),
  CONSTRAINT service_providers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  bio text,
  website character varying,
  social_links jsonb DEFAULT '{}'::jsonb,
  preferences jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  name character varying NOT NULL,
  phone character varying,
  avatar_url text,
  role character varying DEFAULT 'customer'::character varying CHECK (role::text = ANY (ARRAY['customer'::character varying, 'provider'::character varying]::text[])),
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  latitude numeric,
  longitude numeric,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_banned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  agree_to_terms boolean DEFAULT false,
  supabase_auth_id uuid UNIQUE,
  last_sign_in_at timestamp with time zone,
  email_confirmed_at timestamp with time zone,
  phone_confirmed_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);